### ISSUE TITLE
Godot crash upon enabling the addon - or running the repo as a project (pre-enabled)

### ISSUE THREAD

**Issue by CaveHEX** [kanimaru/twitcher#17]
Hello, I have issues running the addon,

Either by : 
- Running the repo as a standalone project.
- Running it in another project after importing the addon.

In both situations having the proper res://addons/twitcher path, I get :

- (1) The popup error : Failed to load script "res://addons/twitcher/plugin.gd" with error "Parse error".
- (2) The (Re)Importing asset stuck at "example-3.gif" - Therefore crashing Godot

Issue (1) happens when opening the repo as a project
Issue (2) happens when opening the repo as a project, and when enabling the addon when imported in another project

> I am running the 4.2.2.stable GDScript version of Godot, the latest version of the repo as of today, on Windows.

I hope that I am not missing something blatantly obvious. Thank you for your time.

**Comment by CaveHEX** [comment]
The gifs in the /documentation directory seemed to be the issue, godot refused to import these. Simply deleting them fixed the issue.

**Comment by kanimaru** [comment]
Yeah the problem is known... Technically the native Gif parser that is in the Lib should take care for it... but somehow you have to manual import Gif files that are already in the project... for new Gifs it seems to work. So I guess that origin is a Godot Editor problem with existing files when new Importer get installed. I think we will remove the Gif file for now...

**Comment by kanimaru** [comment]
Can you check if you still have this problem with latest 4.3 godot version? Cause I couldn't replicate it.

**Comment by kanimaru** [comment]
Cause of no response I close it.
