### ISSUE TITLE
Great new plugin / imagetransformer troubles

### ISSUE THREAD

**Issue by infohub-gather** [kanimaru/twitcher#3]
Thanks for creating this new Twitch integration plugin! :)

The Imagemagick integration is opaque to me, I keep getting the message 
"BUG: File queued for import, but can't be imported, importer for type 'kani_dev.imagemagick' not found" 
I tried setting the imagetransformer to nothing but that doesn't work.

PS What would be cool to have is bare bones connection library (without the cruft of external libraries or opinions of implementations) to design your own functionality. Maybe a TwitcherBasic and TwitcherFull add-on seperately?

But great to see more Twitch addons nonetheless! Thanks Kanimura!

**Comment by kanimaru** [comment]
Hi Infohub-Gather thanks for using the lib. 

> The Imagemagick integration is opaque to me, I keep getting the message
> "BUG: File queued for import, but can't be imported, importer for type 'kani_dev.imagemagick' not found"
> I tried setting the imagetransformer to nothing but that doesn't work.

Did you set the executable into `twitch/general/images/image_magic`? So for windows just `magick`? The lib checks the availibility of this field before adding that Importer to the project. Other quick fix would be to delete the documentation folder. Cause there are the gifs that he tries to convert.

I wanted to make the ImageTransformer exchangable so that you don't need to use any external software. But I heared already from other sources that there are still a problems. Especially with the Native one. The LZW Compression has still a bug have to find another pile of motivation to read into the GIF specs to fix it.

> What would be cool to have is bare bones connection library (without the cruft of external libraries or opinions of implementations) 

Most of the supportive stuff around this library is more a way how to implement it in a solid manner instead of good will and the GIF integration was more like a cherry on top cause Twitch uses Gif for the emojis.

> Maybe a TwitcherBasic and TwitcherFull add-on seperately?
The management of that would be time consuming. I wanted to create a lib that technically everyone no matter if newbe or advanced user can just use. Actually I didn't even want to make this library public in the firstplace but couple of streamer friends that I watched had too much trouble with GIFT  that I started this project. It was not the Idea to make this to my main project :D

But you are right this would be the better solution. Maybe when Godot has a real solution for dependency management.


Also use the git version has some bugfixes that I didn't release on AssetLib yet.

~ Kani ~

**Comment by infohub-gather** [comment]
Hi Kani,

Thanks for responding and you made something really incredible, I like to stress that fact! And that you share it is very gracious!

It is true that GIFT didn't really have an alternative and has a few issues. I already learned more about networking then I set out to do because of it haha.

I also used the AssetLib, so probably that may be the issue right now, I will check this later if I have the time and your imagemagick suggestion.

Thanks again and have good weekend!

**Comment by kanimaru** [comment]
Yo Infohub,

I have now implemented a native GIF version or better ported it from godot 3 to 4. 
Also tried to optimize and fix couple of stuff.

Let me know if you still have trouble to using it for your purpose or if we can close this issue :).

~ Kani ~
